### ISSUE TITLE
findById returns keys with undefined when fields filter is array

### ISSUE THREAD

**Issue by irfankhan-sf** [sourcefuse/loopback4-soft-delete#117]
**Describe the bug**
findById returns keys with undefined when fields filter is array. if fields filter is array it return empty object

**To Reproduce**
1. Create a filter using loopback "fields" filter, fields with array of property. For example:-
`fields: [ "id", "header", "content"],`
2. when we call findById with this fields filter
3. The object keys with undefined values will returned 
returned values:` {id:undefined, header: undefined, content: undefined }`

**Expected behavior**
 It should return object with keys that we pass with fields with array

**Comment by yeshamavani** [comment]
done
