### ISSUE TITLE
Refactor Codebase to Improve Flexibility and Maintainability

### ISSUE THREAD

**Issue by shubhamp-sf** [sourcefuse/loopback4-soft-delete#140]
## Is your feature request related to a problem? Please describe.

The main exports in the package are `SoftCrudRepositoryMixin`, the `SoftCrudRepository` class and one for transaction repo. Aiming to serve the same purpose with different underlying class but with mixin it's possible to pass any other class as base having similar interface as `DefaultCrudRepository` from loopback.

Recently a requirement arrived to make it compatible to somewhat different repository from loopback4-sequelize package called  `SequelizeCrudRepository`. It doesn't completely follows the `DefaultCrudRepository`'s interface as it lacks some irrelevant properties, preventing user from using the mixin wrapping sequelize repository.

What we ended up doing is to solve this is, we created a copy of the soft-delete logic code and created new class similar to `SoftCrudRepository` by just replacing the extended class to the sequelize one and exported it as `SequelizeSoftCrudRepository`. 

**The issue with above approach**
 
This brought up major challenge when it comes to maintaining the code. Like any bug fix or any sort of change is supposed to be made in all four places (mixin, main soft crud, transaction repo and sequelize soft crud repo) plus the additional effort for every change in respective test cases as well.
More than maintainability, users won't be able to utilize soft-delete capabilities in any custom class like the sequelize one that doesn't have all the props like default crud repo, due to the strictness of mixin accepting DefaultCrudRepository constructor as a base class's type (where as the mixin only needs few methods to work correctly namely`findOne`, `findById`, `find`, `updateAll`, `updateById`, `deleteById`, `deleteAll` and `count` ).

## Describe the solution you'd like

By behaviour the soft-delete package only adds extra logic before calling the main crud methods. Like modifying the where filter before the `super.find` is invoked. It doesn't care if the base class received is DefaultCurdRepository or the transaction repo or the sequelize one. All it wants is that, it should have a find method (and few others) that it can call. 

So having the type more explicit than `Constructor<DefaultCrudRepository>` would be more flexible and would cover all the extension cases for Transaction, Sequelize and others we may encounter in future. Doing so will eliminate the need of exporting other classes as everyone can use the mixin universally for each of current and future use cases. Leading us to have no duplicate code.

## Additional context

Implementing the above-described solution will result in a BREAKING CHANGE, but it solves two major problems:

1. It improves the maintainability of the code by removing duplicates.
2. It makes the mixin more adaptable to different base classes beyond just the `DefaultCrudRepository` class.

**Comment by samarpan-b** [comment]
Although I agree with this, but is there a way to ensure its not a breaking change ?

**Comment by shubhamp-sf** [comment]
> Although I agree with this, but is there a way to ensure its not a breaking change ?

The major benefits of implementing proposed solution comes from removing the soft crud **classes**. 
So we would deviate from it, if it remains to be non-breaking (i.e. we keep those duplicate classes).

What can be done instead (as suggested by @akshatdubeysf) is we deprecate the classes in the current version and promote the use of mixin in the notice. Alongside we'll release the major version with above solution.

**Comment by samarpan-b** [comment]
I would agree to @akshatdubeysf 's recommendation
