### ISSUE TITLE
Undo deleted Data

### ISSUE THREAD

**Issue by larsk27** [sourcefuse/loopback4-soft-delete#182]
**Is your feature request related to a problem? Please describe.**

Since you don't have a built-in function to undo the deletion of data (soft deleted, not hard deleted), I am not able to undo the deletion.

**Describe the solution you'd like**

Add please updateById and updateAll Functionality that may restore soft-deleted data. 

Thanks in Advance!

**Comment by larsk27** [comment]
@yeshamavani 
I've updated to version 10.0.0 but the undoSoftDeleteById() and undoSoftDeleteAll() is not available as function?

**Comment by yeshamavani** [comment]
> @yeshamavani I've updated to version 10.0.0 but the undoSoftDeleteById() and undoSoftDeleteAll() is not available as function?

it is available in SoftCrudRepository, are you facing any challenges
