### ISSUE TITLE
Filter mixup in find function when using an or/and condition.

### ISSUE THREAD

**Issue by arnaud16571542** [sourcefuse/loopback4-soft-delete#35]
**Describe the bug**
In soft-crud.repository.base.ts, the find function update the 'filter' parameter to add a 'deleted:false' condition. However, in some case, this is not done correctly  and the filter is incorrectly updated...and so the final query is incorrect.

**To Reproduce**
Example of my filter:
```
in   find(filter?: Filter<T>, options?: Options): Promise<(T & Relations)[]> {
filter is filled like below
{
  order: {[ 'xxx ASC']},
  where: {
    id: {eq: 2},
    myColumn: 42,
    or: {[
       {a:1},
       {b:2}
    ]}
  }
```

The "find" function expect a where filter to start with **where:{AND**: or **where: {OR**. If the where filter doesn't start with an AND array or OR array, the filter expect an object (which is an implicit AND), and add "deleted:false" 

When the object contain an AND / OR **property**, with other properties in the object, the filter is incorrectly updated...and so the final query is incorrect.

```
in soft-crud.repository.base.ts
find(filter?: Filter<T>, options?: Options): Promise<(T & Relations)[]> {
    // Filter out soft deleted entries
    if (
      filter?.where &&
      (filter.where as AndClause<T>).and &&
      (filter.where as AndClause<T>).and.length > 0
    ) {
      (filter.where as AndClause<T>).and.push({
        deleted: false,
      } as Condition<T>);
    } else if (
      filter?.where &&
      (filter.where as OrClause<T>).or &&
      (filter.where as OrClause<T>).or.length > 0
    ) {
      filter.where = {
        and: [
          {
            deleted: false,
          } as Condition<T>,
          {
            or: (filter.where as OrClause<T>).or,
          },
        ],
      };
    } else {
      filter = filter ?? {};
      filter.where = filter.where ?? {};
      (filter.where as Condition<T>).deleted = false;
    **}**
```

**Expected behavior**
The find function should better detect when AND/OR/{} is used, and when **or** or **and** is not alone in the object.

**Screenshots**

**Additional context**

**Comment by arnaud16571542** [comment]
Please, find below my suggestion to improve this code... 

```
in soft-crud.repository.base.ts
find(filter?: Filter<T>, options?: Options): Promise<(T & Relations)[]> {
    // Filter out soft deleted entries
    if (
      filter?.where &&
      Object.keys(filter.where).length == 1 &&
      (filter.where as AndClause<T>).and &&
      (filter.where as AndClause<T>).and.length > 0
    ) {
      (filter.where as AndClause<T>).and.push({
        deleted: false,
      } as Condition<T>);
    } else if (
      filter?.where &&
      Object.keys(filter.where).length == 1 &&
      (filter.where as OrClause<T>).or &&
      (filter.where as OrClause<T>).or.length > 0
    ) {
      filter.where = {
        and: [
          {
            deleted: false,
          } as Condition<T>,
          {
            or: (filter.where as OrClause<T>).or,
          },
        ],
      };
    } else {
      filter = filter ?? {};
      filter.where = filter.where ?? {};
      (filter.where as Condition<T>).deleted = false;
    **}**
```

**Comment by samarpan-b** [comment]
Can you please share what was the problematic query generated here with and/or ? Share me the filter object and query generated by this repository. I am a little curious here.

**Comment by arnaud16571542** [comment]
Hellop. Please a look a the example . The problem is when the "where" clause contains an "or" property.
```
  where: {
    id: {eq: 2},
    myColumn: 42,
    or: {[
       {a:1},
       {b:2}
    ]}
  }
```

Because of this, the code executed is this one:
```
filter.where = {
        and: [
          {
            deleted: false,
          } as Condition<T>,
          {
            or: (filter.where as OrClause<T>).or,
          },
        ],
      };
```
The resulting filter is below:
  where: {
  and: [ deleted:false]
  or: {
    id: {eq: 2},
    myColumn: 42,
    or: {[
       {a:1},
       {b:2}
    ]}
   }
},

Sorry, I can't give you a real example as I already replaced the file soft-crud.repository.base.ts in my project, and this has solved severals bugs.

**Comment by akshatdubeysf** [comment]
@arnaud16571542 I got your point, I see you have raised a PR to fix this, I made a comment on that PR, it would be great if you could check that. Your solution in the PR is great but it has some effects on existing functionality related to finding soft deleted items.
