### ISSUE TITLE
'findOne' in type 'SoftCrudRepository is not assignable to the same property in base type 'DefaultCrudRepository

### ISSUE THREAD

**Issue by Gabriel-BS** [sourcefuse/loopback4-soft-delete#4]
In SoftCrudRepository the function findOne has a different Promise type comparing with DefaultCrudRepository, 

Function in SoftCrudRepository Promise<T | null>: 
![Opera Instantâneo_2019-10-21_174951_github com](https://user-images.githubusercontent.com/54040225/67242148-47fc5100-f42b-11e9-9864-8fa05f9c6db2.png)

Function in DefaultCrudRepository Promise<(T & Relations) | null>:
![Sem título](https://user-images.githubusercontent.com/54040225/67242432-e7b9df00-f42b-11e9-80c7-6beff6a9681e.png)

**Comment by samarpan-b** [comment]
Its fixed with latest.
