### ISSUE TITLE
cant install loopback4-soft-delete : dependency tree problem because of bad loopback/repository version.

### ISSUE THREAD

**Issue by arnaud16571542** [sourcefuse/loopback4-soft-delete#42]
**Describe the bug**
You cant install loopback4-soft-delete because of a dependency tree problem

**To Reproduce**
npm install loopback4-soft-delete

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: myserver@1.0.0
npm ERR! Found: @loopback/repository@3.7.1
npm ERR! node_modules/@loopback/repository
npm ERR!   @loopback/repository@"^3.7.1" from the root project
npm ERR!   @loopback/repository@"^3.7.1" from @loopback/boot@3.4.2
npm ERR!   node_modules/@loopback/boot
npm ERR!     @loopback/boot@"^3.4.2" from the root project
npm ERR!     peer @loopback/boot@"^3.4.0" from loopback4-soft-delete@3.2.2
npm ERR!     node_modules/loopback4-soft-delete
npm ERR!       loopback4-soft-delete@"*" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @loopback/repository@"^3.16.0" from loopback4-soft-delete@3.2.2
npm ERR! node_modules/loopback4-soft-delete
npm ERR!   loopback4-soft-delete@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Expected behavior**
Should install normally without any error

**Additional context**
The problem come from
https://github.com/sourcefuse/loopback4-soft-delete/pull/30 where loopback/repository version was setted from "@loopback/repository":  "^3.2.0" -> "^3.16.0".  Currently, loopback repository version is 3.7.1
https://github.com/loopbackio/loopback-next/blob/master/packages/repository/package.json

**Comment by akshatdubeysf** [comment]
@arnaud16571542 Hi, this was an issue that arised after the [npm v7 release](https://github.blog/2020-10-13-presenting-v7-0-0-of-the-npm-cli/), as they changed the dependency resolution logic in that version, we are yet to update our packages for npm v7, till then you could use npm v6 to use this package without any issue.
