### ISSUE TITLE
findById return EntityNotFound when we using mongodb

### ISSUE THREAD

**Issue by Vn-ChemGio** [sourcefuse/loopback4-soft-delete#43]
When we using loopback4 with database mongodb
We also using id generate by MongoDb with field name _id, without using id field
In SoftCrudRepository into this package , when findById, it using id only

`//As parent method findById have filter: FilterExcludingWhere<T>
    //so we need add check here.
    const entityToRemove = await super.findOne(filter, options);

    if (entityToRemove) {
      // Now call super
      return super.findById(id, filter, options);
    } else {
      throw new HttpErrors.NotFound(ErrorKeys.EntityNotFound);
    }`
That take entityToRemove always null then it return an error

**Comment by akshatdubeysf** [comment]
@faizan1620
