### ISSUE TITLE
Can't use migrate in loopback when use this module

### ISSUE THREAD

**Issue by Vn-ChemGio** [sourcefuse/loopback4-soft-delete#47]
When we implement class SoftCrudRepository from this module 
When run migrate script, it always return an error 
![image](https://user-images.githubusercontent.com/25608423/132224666-a7258efd-b495-426c-862a-de0f203f32df.png)

`Migrating schemas (alter existing schema)
Cannot migrate database schema { ResolutionError: The argument 'BaseEntityDigitalAssetRepository.constructor[0]' is not decorated for dependency injection but no value was supplied by the caller. Did you forget to apply @inject
() to the argument? (context: MainApplication-llRl2lIGS2mNtF2YxaD_Vw-0, resolutionPath: repositories.BaseEntityDigitalAssetRepository)
`

**Comment by akshatdubeysf** [comment]
Hi @Vn-ChemGio ,

Can you share the repository and the model that you are using?

**Comment by Vn-ChemGio** [comment]
> 
> 
> Hi @Vn-ChemGio ,
> 
> Can you share the repository and the model that you are using?

you can create new  project with one or two model and 1 repository file by lb4 cli generator
